#!/usr/bin/env bash
#
# REAL Tour — executable documentation.
# Status: REAL — every line below runs a real binary against real data.
#
# Runs every REAL tool + test suite; emits docs/REAL_TOUR_OUTPUT.md with
# the actual outputs captured this run. If you edit docs/REAL_TOUR_OUTPUT.md
# by hand, this script will overwrite it on the next run — the doc IS the
# execution.
#
# Usage:
#   bash docs/REAL_TOUR.sh              — run the tour, refresh output
#   bash docs/REAL_TOUR.sh --check      — run + fail if any suite red
#
# Exit codes:
#   0 — everything green
#   1 — at least one command failed (only when --check is passed)

set -uo pipefail

CHECK_MODE=0
if [ "${1:-}" = "--check" ]; then CHECK_MODE=1; fi

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$REPO_ROOT"

OUT="docs/REAL_TOUR_OUTPUT.md"
SCRATCH="/tmp/real_tour.$$"
mkdir -p "$SCRATCH"
trap 'rm -rf "$SCRATCH"' EXIT

STATUS_OK=0
STATUS_FAIL=0
mark_ok()   { STATUS_OK=$((STATUS_OK + 1)); }
mark_fail() { STATUS_FAIL=$((STATUS_FAIL + 1)); }

# --- helpers to capture command output into the markdown ---

section() { printf '\n## %s\n\n' "$1" >> "$OUT"; }
subsection() { printf '\n### %s\n\n' "$1" >> "$OUT"; }
para() { printf '%s\n\n' "$1" >> "$OUT"; }

run_capture() {
    # $1 = label, $2 = expected exit code (default 0), rest = command
    local label="$1"; shift
    local want="$1"; shift
    printf '**$ %s**\n\n' "$*" >> "$OUT"
    printf '```\n' >> "$OUT"
    local out rc
    out=$("$@" 2>&1)
    rc=$?
    printf '%s\n' "$out" >> "$OUT"
    printf '```\n\n' >> "$OUT"
    if [ "$rc" -eq "$want" ]; then
        printf '_✓ %s (exit=%d as expected)_\n\n' "$label" "$rc" >> "$OUT"
        mark_ok
    else
        printf '_✗ %s (exit=%d, expected %d)_\n\n' "$label" "$rc" "$want" >> "$OUT"
        mark_fail
    fi
}

# --- build header ---

cat > "$OUT" <<EOF
# REAL Tour — Live Execution Output

Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)
Host: $(uname -srm)
Git commit: $(git rev-parse HEAD 2>/dev/null || echo unknown)

> This file is auto-generated by \`docs/REAL_TOUR.sh\`. Every code block
> below is the exact output of a real command run against real data at
> generation time. Do NOT edit by hand — re-run the tour instead.

---

EOF

section "1. Build every REAL binary"

run_capture "make metrics-producer arch-probe receipt-validate receipt-ledger contract-validate arch-detect pkg-real pkg-count-freestanding" \
    0 make -C core \
    metrics-producer arch-probe receipt-validate receipt-ledger \
    contract-validate arch-detect pkg-real pkg-count-freestanding

section "2. Real inventory of packages"

run_capture "pkg-real inventory" 0 ./core/pkg-real inventory .

subsection "2.1 Real DAG summary"

run_capture "pkg-real dag" 0 bash -c "./core/pkg-real dag . 2>&1 | tail -20"

section "3. Real metrics + signed receipt"

run_capture "metrics-producer" 0 \
    ./core/metrics-producer . "$SCRATCH/m.json"

subsection "3.1 Metrics JSON (head 30 lines)"

printf '```json\n' >> "$OUT"
head -30 "$SCRATCH/m.json" >> "$OUT"
printf '```\n\n' >> "$OUT"

subsection "3.2 Contract validation"

run_capture "contract-validate" 0 ./core/contract-validate "$SCRATCH/m.json"

subsection "3.3 Receipt verification"

run_capture "receipt-validate" 0 ./core/receipt-validate "$SCRATCH/m.json.receipt"

section "4. Chain-of-custody ledger"

LEDGER="$SCRATCH/tour.jsonl"

for i in 1 2 3; do
    ./core/metrics-producer . "$SCRATCH/r$i.json" >/dev/null 2>&1
    ./core/receipt-ledger append "$LEDGER" "$SCRATCH/r$i.json.receipt" >/dev/null 2>&1
done

subsection "4.1 Ledger tail after 3 appends"

run_capture "receipt-ledger tail" 0 ./core/receipt-ledger tail "$LEDGER"

subsection "4.2 Chain verify (intact)"

run_capture "receipt-ledger verify" 0 ./core/receipt-ledger verify "$LEDGER"

subsection "4.3 Tamper detection (edit entry 2, verify must FAIL)"

sed '2s/"receipt_sha256":"[a-f0-9]\{16\}/"receipt_sha256":"deadbeefdeadbeef/' \
    "$LEDGER" > "$SCRATCH/tampered.jsonl"

run_capture "verify tampered ledger" 1 \
    ./core/receipt-ledger verify "$SCRATCH/tampered.jsonl"

section "5. Runtime capability probe (Phase 10)"

run_capture "arch-probe" 0 ./core/arch-probe "$SCRATCH/cap.json"

subsection "5.1 Capability JSON"

printf '```json\n' >> "$OUT"
cat "$SCRATCH/cap.json" >> "$OUT"
printf '```\n\n' >> "$OUT"

section "6. Architecture matrix"

run_capture "arch-detect --json (head 20 lines)" 0 \
    bash -c "./core/arch-detect --json 2>&1 | head -20"

section "7. Freestanding pkg counter (no libc, no CRT)"

run_capture "pkg-count-freestanding" 0 ./core/pkg-count-freestanding .

subsection "7.1 Binary is fully static, no dynamic linker"

run_capture "file core/pkg-count-freestanding" 0 \
    file core/pkg-count-freestanding

section "8. Full governance gate (10 stages)"

# Use scratch ledger dir so we don't collide with the tour's ledger
mkdir -p "$SCRATCH/gov"
LEDGER_PATH="$SCRATCH/gov/ledger.jsonl" \
LEDGER_DIR="$SCRATCH/gov" \
run_capture "scripts/real_governance.sh" 0 \
    bash -c "LEDGER_PATH='$SCRATCH/gov/ledger.jsonl' LEDGER_DIR='$SCRATCH/gov' bash scripts/real_governance.sh 2>&1 | tail -20"

section "9. All REAL test suites"

for suite in test-pkg-real:./core/test-pkg-real \
             tests/test_real_attrs.sh:bash \
             tests/test_freestanding.sh:bash \
             tests/test_governance.sh:bash \
             tests/test_arch.sh:bash \
             tests/test_receipts.sh:bash \
             tests/test_ledger.sh:bash \
             tests/test_arch_probe.sh:bash; do
    name=${suite%%:*}
    runner=${suite##*:}
    subsection "9.$STATUS_OK $name"
    if [ "$runner" = "bash" ]; then
        run_capture "$name" 0 bash -c "$runner core/$name 2>&1 | tail -6"
    else
        run_capture "$name" 0 bash -c "$runner 2>&1 | tail -6"
    fi
done

section "10. Summary"

cat >> "$OUT" <<EOF
| Metric | Value |
|---|---:|
| Commands run | $((STATUS_OK + STATUS_FAIL)) |
| ✓ passed | $STATUS_OK |
| ✗ failed | $STATUS_FAIL |
| Host | $(uname -srm) |
| Git commit | $(git rev-parse HEAD 2>/dev/null || echo unknown) |
| Generated at | $(date -u +%Y-%m-%dT%H:%M:%SZ) |

---

_Every line above was produced by executing the corresponding command at
tour time. To reproduce: \`bash docs/REAL_TOUR.sh\`. To fail-closed in
CI on any regression: \`bash docs/REAL_TOUR.sh --check\`._
EOF

echo ""
echo "=== REAL Tour complete ==="
echo "Passed: $STATUS_OK"
echo "Failed: $STATUS_FAIL"
echo "Output: $OUT"

if [ "$CHECK_MODE" -eq 1 ] && [ "$STATUS_FAIL" -gt 0 ]; then
    exit 1
fi
exit 0
